# Generated by Django 2.2 on 2020-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント情報'},
        ),
        migrations.AlterModelOptions(
            name='eventkouhonichiji',
            options={'verbose_name': 'イベント候補日時情報'},
        ),
        migrations.AlterModelOptions(
            name='sankanichiji',
            options={'verbose_name': '参加日時情報'},
        ),
        migrations.AlterModelOptions(
            name='sankasha',
            options={'verbose_name': '参加者情報'},
        ),
        migrations.AddField(
            model_name='event',
            name='anshou_num',
            field=models.IntegerField(default=0, max_length=4, verbose_name='暗証番号'),
            preserve_default=False,
        ),
    ]
