# Generated by Django 2.2 on 2020-08-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sankasha_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkouhonichiji',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_kouho_nichiji_set', to='home.Event', verbose_name='イベント'),
        ),
        migrations.AlterField(
            model_name='sankanichiji',
            name='event_kouho_nichiji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_kouho_sanka_nichiji_set', to='home.EventKouhoNichiji', verbose_name='イベント候補日時'),
        ),
        migrations.AlterField(
            model_name='sankanichiji',
            name='sankasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sankasha_sanka_nichiji_set', to='home.Sankasha', verbose_name='参加者'),
        ),
        migrations.AlterField(
            model_name='sankasha',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sankasha_set', to='home.Event', verbose_name='イベント'),
        ),
    ]
