# Generated by Django 2.2 on 2020-08-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='イベント名')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='EventKouhoNichiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kouho_nichiji', models.CharField(max_length=255, verbose_name='候補日時')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_kouhobis', to='home.Event', verbose_name='イベント')),
            ],
        ),
        migrations.CreateModel(
            name='Sankasha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='参加者名')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sankashas', to='home.Event', verbose_name='イベント')),
            ],
        ),
        migrations.CreateModel(
            name='SankaNichiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanka_kahi', models.IntegerField(verbose_name='参加可否')),
                ('event_kouho_nichiji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sanka_nichiji', to='home.EventKouhoNichiji', verbose_name='イベント候補日時')),
                ('sankasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sanka_nichiji', to='home.Sankasha', verbose_name='参加者')),
            ],
        ),
    ]
