# Generated by Django 2.2 on 2020-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200823_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule_update_id',
            field=models.CharField(default='', max_length=64, verbose_name='スケジュール更新ID'),
            preserve_default=False,
        ),
    ]
