# Generated by Django 2.2 on 2020-08-24 13:15

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_schedule_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sankasha',
            name='anshou_num',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.MinLengthValidator(4), home.models.only_intger], verbose_name='暗証番号'),
            preserve_default=False,
        ),
    ]
