# Generated by Django 2.2 on 2020-08-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200824_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sankasha',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='コメント'),
        ),
    ]
