version: "3.4"

# ※本ファイル内で使用している変数は「docker-compose.***.env」にkey=value形式で定義されている。
# linksは削除。docker-composeのnetwork機能（無指定で機能する）により各コンテナ内で各サービス名がホスト名として利用できるため。

services:
  #############################################
  # Database
  #############################################
  nuxtboot-h2:
    container_name: nuxtboot-h2
    build:
      context: ./db
    environment:
      H2_WEB_PORT: ${H2_WEB_PORT}
      H2_TCP_PORT: ${H2_TCP_PORT}
      H2_PASSWORD: ${H2_PASSWORD}
    command: >
      sh -c '
          java -cp /var/db/h2-1.4.200.jar org.h2.tools.Server -webAllowOthers -tcpAllowOthers -tcpPassword "${H2_PASSWORD}" -webPort "${H2_WEB_PORT}" -tcpPort "${H2_TCP_PORT}"
      '
    expose:
      - ${H2_WEB_PORT}
      - ${H2_TCP_PORT}
    # デバッグでDBの中身を確認できるよう、ホストにもポートを開放
    ports:
      - ${H2_WEB_PORT}:${H2_WEB_PORT}
      - ${H2_TCP_PORT}:${H2_TCP_PORT}
    volumes:
      # データ永続化先を指定
      - ./db:${DB_PATH}

  #############################################
  # WEB APP
  #############################################
  nuxtboot-app:
    container_name: nuxtboot-app
    build:
      context: ./app
    expose:
      - 8585
    depends_on:
      - nuxtboot-h2
    volumes:
      - ./app:/opt/app
      - ./db:${DB_PATH} # h2jar利用のため

    working_dir: /opt/app
    command: >
      sh -c '
        sh /wait-for-h2.sh nuxtboot-h2:"${H2_TCP_PORT}" "${H2_USER}" "${H2_PASSWORD}" java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar nuxtboot-app-${APP_VERSION}.jar
      '
    environment:
      DB_SCHEMA_NAME: ${DB_SCHEMA_NAME}
      DB_ADMIN_USER_NAME: ${H2_USER}
      DB_ADMIN_USER_PASS: ${H2_PASSWORD}
      DB_PATH: ${DB_PATH}
      DB_SERVER: nuxtboot-h2
      DB_PORT: ${H2_TCP_PORT}

  #############################################
  # Webサーバ
  #############################################
  nuxtboot-nginx:
    container_name: nuxtboot-nginx
    build:
      context: ./nginx
    environment:
      TZ: Asia/Tokyo
      LETSENCRYPT_HOSTS: nuxtboot.isomurt.0g0.jp
      LETSENCRYPT_MAIL: isoittech@gmail.com
      LETSENCRYPT_SUBJECT: "/C=JP/ST=Tokyo/L=Shinagawa/CN=default"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxtboot-app
    volumes:
      # nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # log directory
      - /var/log/nginx:/var/log/nginx
      # document root directory
      #- /var/www/html:/var/www/html
      - /home/app-user/App/nuxtboot:/opt/app/nuxtboot
